controllers/RssController.php
<?php


namespace app\controllers;


use app\models\rss\analyzer\Counter;
use app\models\rss\analyzer\FormNormalizer;
use app\models\rss\analyzer\FrequentWordAnalyzer;
use app\models\rss\analyzer\PopularFilter;
use app\models\rss\analyzer\ShortNormalizer;
use app\models\rss\analyzer\WordSeparator;
use app\models\rss\RssDataProvider;
use app\models\rss\source\Source;
use yii\filters\AccessControl;
use yii\web\Controller;

class RssController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    public function actionIndex()
    {
        $rssProvider = new RssDataProvider(new Source(\Yii::$app->params['rss_url']));
        $analyzer = new FrequentWordAnalyzer();
        $analyzer->setSeparator(new WordSeparator())
            ->setCounter(new Counter())
            ->addHandlers(new ShortNormalizer())
            ->addHandlers(new FormNormalizer())
            ->addHandlers(new PopularFilter());

        return $this->render('index', [
            'rssProvider' => $rssProvider,
            'analyzer' => $analyzer
        ]);
    }


}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\rss\analyzer\FrequentWordAnalyzer;
use app\models\rss\analyzer\PopularFilter;
use app\models\rss\analyzer\RssDataProvider;
use app\models\rss\analyzer\source\Source;
use app\models\rss\analyzer\WordSeparator;
use app\models\user\LoginForm;
use app\models\user\RegistryForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\widgets\ActiveForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string|array
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRegistry()
    {
        $model = new RegistryForm();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if ($model->load(Yii::$app->request->post()) && $model->registry()) {
            return $this->redirect(['site/index']);
        }
        return $this->render('registry', [
            'model' => $model
        ]);
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'RSS', 'url' => ['/rss/index']],
            ['label' => 'Registry', 'url' => ['/site/registry'], 'visible' => Yii::$app->user->isGuest],
            ['label' => 'Login', 'url' => ['/site/login'], 'visible' => Yii::$app->user->isGuest],
            ['label' => 'Logout', 'url' => ['/site/logout'], 'visible' => !Yii::$app->user->isGuest]
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/rss/_itemView.php
<?php
/**
 * @var $model \app\models\rss\Item
 */
?>
<div>
    <p>Author: <?= $model->authorName ?></p>
    <p><?= $model->title ?></p>
    <p><?= strip_tags($model->summary) ?></p>
    <?= \yii\helpers\Html::a($model->link, $model->link, ['target' => '_blank']) ?>
</div>

views/rss/index.php
<?php

/* @var $this \yii\web\View */
/* @var $rssProvider \app\models\rss\RssDataProvider */
/* @var $analyzer \app\models\rss\analyzer\FrequentWordAnalyzer */
$items = $rssProvider->getFeed();
$dataProvider = new \yii\data\ArrayDataProvider([
    'allModels' => $items,
    'pagination' => [
        'pageSize' => 20
    ]
])
?>

<div class="top-words">
    <h2>10 most frequent words</h2>
    <ul>
        <?php
        foreach ($analyzer->getTop($items) as $word => $count) {
            echo \yii\helpers\Html::tag("li", "{$word}: {$count}");
        }
        ?>
    </ul>
</div>

<div class="rss-feed">
    <h2>Feed</h2>
    <?= \yii\widgets\ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_itemView',
        'separator' => '<hr/>'
    ])?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/registry.php
<?php
/* @var $this \yii\web\View */
/* @var $model \app\models\user\RegistryForm */
$this->title = 'Registry';
$this->params['breadcrumbs'][] = $this->title;

use yii\bootstrap\ActiveForm;
use yii\helpers\Html; ?>

<div class="site-registry">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'registry-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'email', ['enableAjaxValidation' => true])->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Registry', ['class' => 'btn btn-primary', 'name' => 'registry-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>